#!/usr/bin/env python
"""from https://github.com/Jvanrhijn/polybar-spotify"""
import dbus
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-t', type=int, default=100)
parser.add_argument('-f', type=str, default='{status} {artist}: {title}')
parser.add_argument('-p', type=str, default=",️")

args = parser.parse_args()

trunclen = args.t
output = args.f
play_pause = args.p.split(",")
session_bus = dbus.SessionBus()
try:
    spotify_bus = session_bus.get_object('org.mpris.MediaPlayer2.spotify', '/org/mpris/MediaPlayer2')
except dbus.exceptions.DBusException:
    exit()
spotify_properties = dbus.Interface(spotify_bus, "org.freedesktop.DBus.Properties")
metadata = spotify_properties.Get('org.mpris.MediaPlayer2.Player', 'Metadata')
title = metadata["xesam:title"]
artist = ",".join(metadata["xesam:artist"])
status = play_pause[0] if spotify_properties.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus') == "Playing" else play_pause[1]

to_print = output.format(
    status=status,
    title=title,
    artist=artist
)
print(to_print[:trunclen] + ("..." if len(to_print) > trunclen else ""))
